In [ ]:
'''
D532 Final Project
Milestone 2 -- Code
Pranav Balaji and Carson Smalarz
'''

'\nD532 Final Project\nMilestone 2 -- Code\nPranav Balaji and Carson Smalarz\n'

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### Preprocessing

In [ ]:
# Carson
df = pd.read_csv("tcc_ceds_music.csv")
df.rename(columns={"Unnamed: 0": "id", "release_date": "release_year"}, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28372 entries, 0 to 28371
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        28372 non-null  int64
 1   artist_name               28372 non-null  object
 2   track_name                28372 non-null  object
 3   release_year              28372 non-null  int64
 4   genre                     28372 non-null  object
 5   lyrics                    28372 non-null  object
 6   len                       28372 non-null  int64
 7   dating                    28372 non-null  float64
 8   violence                  28372 non-null  float64
 9   world/life                28372 non-null  float64
 10  night/time                28372 non-null  float64
 11  shake the audience        28372 non-null  float64
 12  family/gospel             28372 non-null  float64
 13  romantic                  28372 non-null  float64
 14  communication             28372 non-null  float64
 15  obscene                   28372 non-null  float64
 16  music                     28372 non-null  float64
 17  movement/places           28372 non-null  float64
 18  light/visual perceptions  28372 non-null  float64
 19  family/spiritual          28372 non-null  float64
 20  like/girls                28372 non-null  float64
 21  sadness                   28372 non-null  float64
 22  feelings                  28372 non-null  float64
 23  danceability              28372 non-null  float64
 24  loudness                  28372 non-null  float64
 25  acousticness              28372 non-null  float64
 26  instrumentalness          28372 non-null  float64
 27  valence                   28372 non-null  float64
 28  energy                    28372 non-null  float64
 29  topic                     28372 non-null  object
 30  age                       28372 non-null  float64
dtypes: float64(23), int64(3), object(5)
memory usage: 6.7+ MB

In [ ]:
# Carson
df.isna().sum()

id                          0
artist_name                 0
track_name                  0
release_year                0
genre                       0
lyrics                      0
len                         0
dating                      0
violence                    0
world/life                  0
night/time                  0
shake the audience          0
family/gospel               0
romantic                    0
communication               0
obscene                     0
music                       0
movement/places             0
light/visual perceptions    0
family/spiritual            0
like/girls                  0
sadness                     0
feelings                    0
danceability                0
loudness                    0
acousticness                0
instrumentalness            0
valence                     0
energy                      0
topic                       0
age                         0
dtype: int64

In [ ]:
df['id'].describe()

count    28372.000000
mean     42946.323558
std      24749.325492
min          0.000000
25%      20391.250000
50%      45405.500000
75%      64090.500000
max      82451.000000
Name: id, dtype: float64

id column isn't ordered and the numbers are erratic. Hence we would be creating a new id column that increments by one each time.

In [ ]:
#Pranav
df['id_old']=df['id']
len_id=len(df)
for i in range(len_id):
    df['id'][i]=i+1
df.head()
df.drop(columns=['id_old', 'age'])

,id,artist_name,track_name,release_year,genre,lyrics,len,dating,violence,world/life,...,like/girls,sadness,feelings,danceability,loudness,acousticness,instrumentalness,valence,energy,topic
0,1,mukesh,mohabbat bhi jhoothi,1950,pop,hold time feel break feel untrue convince spea...,95,0.000598,0.063746,0.000598,...,0.000598,0.380299,0.117175,0.357739,0.454119,0.997992,0.901822,0.339448,0.137110,sadness
1,2,frankie laine,i believe,1950,pop,believe drop rain fall grow believe darkest ni...,51,0.035537,0.096777,0.443435,...,0.001284,0.001284,0.001284,0.331745,0.647540,0.954819,0.000002,0.325021,0.263240,world/life
2,3,johnnie ray,cry,1950,pop,sweetheart send letter goodbye secret feel bet...,24,0.002770,0.002770,0.002770,...,0.002770,0.002770,0.225422,0.456298,0.585288,0.840361,0.000000,0.351814,0.139112,music
3,4,pérez prado,patricia,1950,pop,kiss lips want stroll charm mambo chacha merin...,54,0.048249,0.001548,0.001548,...,0.081132,0.225889,0.001548,0.686992,0.744404,0.083935,0.199393,0.775350,0.743736,romantic
4,5,giorgos papadopoulos,apopse eida oneiro,1950,pop,till darling till matter know till dream live ...,48,0.001350,0.001350,0.417772,...,0.001350,0.068800,0.001350,0.291671,0.646489,0.975904,0.000246,0.597073,0.394375,romantic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28367,28368,mack 10,10 million ways,2019,hip hop,cause fuck leave scar tick tock clock come kno...,78,0.001350,0.001350,0.001350,...,0.001350,0.065664,0.001350,0.889527,0.759711,0.062549,0.000000,0.751649,0.695686,obscene
28368,28369,m.o.p.,ante up (robbin hoodz theory),2019,hip hop,minks things chain ring braclets yap fame come...,67,0.001284,0.001284,0.035338,...,0.040811,0.001284,0.001284,0.662082,0.789580,0.004607,0.000002,0.922712,0.797791,obscene
28369,28370,nine,whutcha want?,2019,hip hop,get ban get ban stick crack relax plan attack ...,77,0.001504,0.154302,0.168988,...,0.001504,0.001504,0.001504,0.663165,0.726970,0.104417,0.000001,0.838211,0.767761,obscene
28370,28371,will smith,switch,2019,hip hop,check check yeah yeah hear thing call switch g...,67,0.001196,0.001196,0.001196,...,0.070867,0.001196,0.001196,0.883028,0.786888,0.007027,0.000503,0.508450,0.885882,obscene
28371,28372,jeezy,r.i.p.,2019,hip hop,remix killer alive remix thriller trap bitch s...,83,0.001012,0.075202,0.001012,...,0.001012,0.001012,0.033995,0.828875,0.674794,0.015862,0.000000,0.475474,0.492477,obscene

In [ ]:
df.head(10)

,id,artist_name,track_name,release_year,genre,lyrics,len,dating,violence,world/life,...,feelings,danceability,loudness,acousticness,instrumentalness,valence,energy,topic,age,id_old
0,1,mukesh,mohabbat bhi jhoothi,1950,pop,hold time feel break feel untrue convince spea...,95,0.000598,0.063746,0.000598,...,0.117175,0.357739,0.454119,0.997992,0.901822,0.339448,0.137110,sadness,1.0,0
1,2,frankie laine,i believe,1950,pop,believe drop rain fall grow believe darkest ni...,51,0.035537,0.096777,0.443435,...,0.001284,0.331745,0.647540,0.954819,0.000002,0.325021,0.263240,world/life,1.0,4
2,3,johnnie ray,cry,1950,pop,sweetheart send letter goodbye secret feel bet...,24,0.002770,0.002770,0.002770,...,0.225422,0.456298,0.585288,0.840361,0.000000,0.351814,0.139112,music,1.0,6
3,4,pérez prado,patricia,1950,pop,kiss lips want stroll charm mambo chacha merin...,54,0.048249,0.001548,0.001548,...,0.001548,0.686992,0.744404,0.083935,0.199393,0.775350,0.743736,romantic,1.0,10
4,5,giorgos papadopoulos,apopse eida oneiro,1950,pop,till darling till matter know till dream live ...,48,0.001350,0.001350,0.417772,...,0.001350,0.291671,0.646489,0.975904,0.000246,0.597073,0.394375,romantic,1.0,12
5,6,perry como,round and round (with mitchell ayres and his o...,1950,pop,convoy light dead ahead merchantmen trump dies...,98,0.001053,0.420685,0.001053,...,0.001053,0.689158,0.685588,0.898594,0.000000,0.768137,0.549535,violence,1.0,14
6,7,freestyle,opm medley: when i met you,1950,pop,piece mindin world knowin life come bring give...,179,0.000483,0.000483,0.371817,...,0.123150,0.368569,0.633695,0.435742,0.000000,0.282770,0.486470,world/life,1.0,15
7,8,johnny mathis,it's not for me to say,1950,pop,care moment hold fast press lips dream heaven ...,21,0.002506,0.002506,0.336056,...,0.002506,0.379400,0.529421,0.925703,0.000072,0.373454,0.192167,world/life,1.0,17
8,9,stélios kazantzídis,klapse me mana klapse me,1950,pop,lonely night surround power read mind hour nig...,30,0.083537,0.002024,0.002024,...,0.031600,0.496372,0.666180,0.974900,0.000014,0.621805,0.400382,romantic,1.0,20
9,10,stélios kazantzídis,finito la mouzika,1950,pop,tear heart seat stay awhile tear heart game st...,61,0.001120,0.102548,0.001120,...,0.001120,0.662082,0.643130,0.983936,0.000175,0.744435,0.413395,sadness,1.0,23

### Connect to MongoDB using PyMongo

In [ ]:
# Carson
!pip install pymongo
import pymongo
from pprint import pprint
client = pymongo.MongoClient("mongodb+srv://spotifymoodexploration_db_user:music123pc@spotify-mood-exploratio.suiotpe.mongodb.net/")

Collecting pymongo
  Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 20.7 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 24.1 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.16.0

Upload the data to the database

In [ ]:
# Carson
db = client['Final_Project']
collection = db['Music']
#dic = df.to_dict(orient='records')
#collection.insert_many(dic)

In [ ]:
# pranav
collection.update_many(
    {},
    {"$unset": {"id_old": ""}}
)

UpdateResult({'n': 28372, 'electionId': ObjectId('7fffffff000000000000023f'), 'opTime': {'ts': Timestamp(1775238376, 8010), 't': 575}, 'nModified': 28372, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1775238376, 8010), 'signature': {'hash': b'I\xadb\xd5\xef\xf5\x98\x04\xf8\xbbh\xabM7S\xa3\xfe\xe0K\xf7', 'keyId': 7592249427562070021}}, 'operationTime': Timestamp(1775238376, 8010), 'updatedExisting': True}, acknowledged=True)

### MongoDB Queries

In [ ]:
#pranav
collection.find_one()

{'_id': ObjectId('69cff034cf79a87798eadf6e'),
 'id': 1,
 'artist_name': 'mukesh',
 'track_name': 'mohabbat bhi jhoothi',
 'release_year': 1950,
 'genre': 'pop',
 'lyrics': 'hold time feel break feel untrue convince speak voice tear try hold hurt try forgive okay play break string feel heart want feel tell real truth hurt lie worse anymore little turn dust play house ruin run leave save like chase train late late tear try hold hurt try forgive okay play break string feel heart want feel tell real truth hurt lie worse anymore little run leave save like chase train know late late play break string feel heart want feel tell real truth hurt lie worse anymore little know little hold time feel',
 'len': 95,
 'dating': 0.0005980861262889,
 'violence': 0.0637461276114993,
 'world/life': 0.0005980861568711,
 'night/time': 0.0005980861851733,
 'shake the audience': 0.0005980861274492,
 'family/gospel': 0.048857015216959,
 'romantic': 0.0171043388602836,
 'communication': 0.2637508813174463,
 'obscene': 0.0005980861613241,
 'music': 0.0392883659255256,
 'movement/places': 0.000598086192264,
 'light/visual perceptions': 0.0005980861380272,
 'family/spiritual': 0.0005980861261369,
 'like/girls': 0.000598086179608,
 'sadness': 0.380298895230333,
 'feelings': 0.1171754514230962,
 'danceability': 0.3577385465179248,
 'loudness': 0.4541189139296976,
 'acousticness': 0.9979919658553876,
 'instrumentalness': 0.901821862348178,
 'valence': 0.3394476504534212,
 'energy': 0.1371101880258922,
 'topic': 'sadness',
 'age': 1.0}

In [ ]:
#pranav
collection.count_documents({})

28372

In [ ]:
#pranav
pipeline = [
    {"$group": {"_id":"$genre", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}},
    {"$project": {"_id": 0, "genre": "$_id", "count": 1}}
]

results=collection.aggregate(pipeline)
print("Top 7 genres")
for i, result in enumerate(results, 1):
  print(f"{i}. {result["genre"]}: {result["count"]}")

Top 7 genres
1. pop: 7042
2. country: 5445
3. blues: 4604
4. rock: 4034
5. jazz: 3845
6. reggae: 2498
7. hip hop: 904

In [ ]:
# Carson

top_loud = collection.find(
    {},
    {"_id": 0, "artist_name": 1, "track_name": 1, "loudness": 1}
).sort("loudness", pymongo.DESCENDING).limit(10)

print("Top 10 Loudest Songs")
for i, song in enumerate(top_loud, 1):
  print(f"{i}. \"{song["track_name"]}\" by {song["artist_name"]}: {round(song["loudness"], 3)} loudness")

Top 10 Loudest Songs
1. "the drag" by ty segall: 1.0 loudness
2. "fading all away" by jay reatard: 0.968 loudness
3. "death trip" by the stooges: 0.965 loudness
4. "hold me tight" by the king khan & bbq show: 0.945 loudness
5. "let me hear" by fear, and loathing in las vegas: 0.94 loudness
6. "search and destroy" by the stooges: 0.937 loudness
7. "death is forming" by jay reatard: 0.934 loudness
8. "greed, money, useless children" by jay reatard: 0.934 loudness
9. "where my money" by royce da 5'9": 0.932 loudness
10. "nightmares" by jay reatard: 0.922 loudness

In [ ]:
# Carson
pipeline = [
    {"$group": {
        "_id": "$artist_name",
        "avg_length": {"$avg": "$len"}
    }},
    {"$sort": {"avg_length": -1}},
    {"$limit": 10},
    {"$project": {
        "_id" : 0,
        "artist_name": "$_id",
        "avg_length" : 1
    }}
]

results = collection.aggregate(pipeline)
print("Top 10 Artists With Longest Lyrics")
for result in results:
  print(f"{result["artist_name"]}: {result["avg_length"]}")

Top 10 Artists With Longest Lyrics
chris webby: 199.0
sergio vega "el shaka": 199.0
quavo: 199.0
beanie sigel: 199.0
sam gendel: 199.0
travis barker: 199.0
brotha lynch hung: 198.0
carl sims: 198.0
mime 871: 198.0
mc duke: 198.0

In [ ]:
# Pranav
pipeline = [{
    "$addFields": {
        "bedtime_score": {
            "$subtract": [
                {
                    "$add": [
                        {"$multiply": ["$night/time", 3]},
                        {"$multiply": ["$family/gospel",3]},
                        {"$multiply": ["$family/spiritual", 3]},
                        "$acousticness"
                    ]
                },
                {
                  "$add": [
                      {"$multiply": ["$obscene", 4]},
                      {"$multiply": ["$violence",3]},
                      {"$multiply": ["$energy", 1.5]},
                  ]
                }
            ]
        }
    }

},{
    "$sort": {"bedtime_score": -1}
            },
            {
                "$limit": 10
            }
            ,
{

    "$project": {
        "_id": 0,
        "artist_name": 1,
        "track_name": 1,
        "bedtime_score": 1
}
}
]

results = collection.aggregate(pipeline)
print("Top 10 Bedtime Songs")
for result in results:
  print(f"{result['track_name']} by {result['artist_name']}: {round(result['bedtime_score'],3)}")

Top 10 Bedtime Songs
you and me by joe pass: 3.431
hard time killin' floor blues by skip james: 3.364
corrinna, corrinna by mississippi john hurt: 3.054
bookends by simon & garfunkel: 3.018
right, wrong or ready by karen dalton: 2.987
silent night by bing crosby: 2.924
silent night by sinéad o'connor: 2.868
vieni su (say you love me, too) by dean martin: 2.693
silent night by nat king cole: 2.66
st. joseph's by the avett brothers: 2.633

In [ ]:
#Acknowledgements - Query format provided by Claude 2.5 Sonet, 2026-04-03.